
/*
Auto-generated by CVXPYgen on August 20, 2023 at 23:19:56.
Content: Python binding with pybind11.
*/

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <ctime>
#include "cpg_module.hpp"

extern "C" {
    #include "include/cpg_workspace.h"
    #include "include/cpg_solve.h"
}

namespace py = pybind11;

static int i;

CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp){

    // Pass changed user-defined parameter values to the solver
    if (CPG_Updated_cpp.x_final) {
        for(i=0; i<2; i++) {
            cpg_update_x_final(i, CPG_Params_cpp.x_final[i]);
        }
    }
    if (CPG_Updated_cpp.x_init) {
        for(i=0; i<2; i++) {
            cpg_update_x_init(i, CPG_Params_cpp.x_init[i]);
        }
    }
    if (CPG_Updated_cpp.A) {
        for(i=0; i<4; i++) {
            cpg_update_A(i, CPG_Params_cpp.A[i]);
        }
    }
    if (CPG_Updated_cpp.B) {
        for(i=0; i<2; i++) {
            cpg_update_B(i, CPG_Params_cpp.B[i]);
        }
    }

    // Solve
    std::clock_t ASA_start = std::clock();
    cpg_solve();
    std::clock_t ASA_end = std::clock();

    // Arrange and return results
    CPG_Prim_cpp_t CPG_Prim_cpp {};
    for(i=0; i<22; i++) {
        CPG_Prim_cpp.X[i] = CPG_Prim.X[i];
    }
    for(i=0; i<10; i++) {
        CPG_Prim_cpp.U[i] = CPG_Prim.U[i];
    }
    CPG_Dual_cpp_t CPG_Dual_cpp {};
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d0[i] = CPG_Dual.d0[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d1[i] = CPG_Dual.d1[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d2[i] = CPG_Dual.d2[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d3[i] = CPG_Dual.d3[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d4[i] = CPG_Dual.d4[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d5[i] = CPG_Dual.d5[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d6[i] = CPG_Dual.d6[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d7[i] = CPG_Dual.d7[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d8[i] = CPG_Dual.d8[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d9[i] = CPG_Dual.d9[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d10[i] = CPG_Dual.d10[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d11[i] = CPG_Dual.d11[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d12[i] = CPG_Dual.d12[i];
    }
    CPG_Dual_cpp.d13 = CPG_Dual.d13;
    CPG_Dual_cpp.d14 = CPG_Dual.d14;
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d15[i] = CPG_Dual.d15[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d16[i] = CPG_Dual.d16[i];
    }
    CPG_Dual_cpp.d17 = CPG_Dual.d17;
    CPG_Dual_cpp.d18 = CPG_Dual.d18;
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d19[i] = CPG_Dual.d19[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d20[i] = CPG_Dual.d20[i];
    }
    CPG_Dual_cpp.d21 = CPG_Dual.d21;
    CPG_Dual_cpp.d22 = CPG_Dual.d22;
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d23[i] = CPG_Dual.d23[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d24[i] = CPG_Dual.d24[i];
    }
    CPG_Dual_cpp.d25 = CPG_Dual.d25;
    CPG_Dual_cpp.d26 = CPG_Dual.d26;
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d27[i] = CPG_Dual.d27[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d28[i] = CPG_Dual.d28[i];
    }
    CPG_Dual_cpp.d29 = CPG_Dual.d29;
    CPG_Dual_cpp.d30 = CPG_Dual.d30;
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d31[i] = CPG_Dual.d31[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d32[i] = CPG_Dual.d32[i];
    }
    CPG_Dual_cpp.d33 = CPG_Dual.d33;
    CPG_Dual_cpp.d34 = CPG_Dual.d34;
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d35[i] = CPG_Dual.d35[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d36[i] = CPG_Dual.d36[i];
    }
    CPG_Dual_cpp.d37 = CPG_Dual.d37;
    CPG_Dual_cpp.d38 = CPG_Dual.d38;
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d39[i] = CPG_Dual.d39[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d40[i] = CPG_Dual.d40[i];
    }
    CPG_Dual_cpp.d41 = CPG_Dual.d41;
    CPG_Dual_cpp.d42 = CPG_Dual.d42;
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d43[i] = CPG_Dual.d43[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d44[i] = CPG_Dual.d44[i];
    }
    CPG_Dual_cpp.d45 = CPG_Dual.d45;
    CPG_Dual_cpp.d46 = CPG_Dual.d46;
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d47[i] = CPG_Dual.d47[i];
    }
    for(i=0; i<2; i++) {
        CPG_Dual_cpp.d48[i] = CPG_Dual.d48[i];
    }
    CPG_Dual_cpp.d49 = CPG_Dual.d49;
    CPG_Dual_cpp.d50 = CPG_Dual.d50;
    CPG_Info_cpp_t CPG_Info_cpp {};
    CPG_Info_cpp.obj_val = CPG_Info.obj_val;
    CPG_Info_cpp.iter = CPG_Info.iter;
    CPG_Info_cpp.status = CPG_Info.status;
    CPG_Info_cpp.pri_res = CPG_Info.pri_res;
    CPG_Info_cpp.dua_res = CPG_Info.dua_res;
    CPG_Info_cpp.time = 1.0*(ASA_end-ASA_start) / CLOCKS_PER_SEC;
    CPG_Result_cpp_t CPG_Result_cpp {};
    CPG_Result_cpp.prim = CPG_Prim_cpp;
    CPG_Result_cpp.dual = CPG_Dual_cpp;
    CPG_Result_cpp.info = CPG_Info_cpp;
    return CPG_Result_cpp;

}

PYBIND11_MODULE(cpg_module, m) {

    py::class_<CPG_Params_cpp_t>(m, "cpg_params")
            .def(py::init<>())
            .def_readwrite("x_final", &CPG_Params_cpp_t::x_final)
            .def_readwrite("x_init", &CPG_Params_cpp_t::x_init)
            .def_readwrite("A", &CPG_Params_cpp_t::A)
            .def_readwrite("B", &CPG_Params_cpp_t::B)
            ;

    py::class_<CPG_Updated_cpp_t>(m, "cpg_updated")
            .def(py::init<>())
            .def_readwrite("x_final", &CPG_Updated_cpp_t::x_final)
            .def_readwrite("x_init", &CPG_Updated_cpp_t::x_init)
            .def_readwrite("A", &CPG_Updated_cpp_t::A)
            .def_readwrite("B", &CPG_Updated_cpp_t::B)
            ;

    py::class_<CPG_Prim_cpp_t>(m, "cpg_prim")
            .def(py::init<>())
            .def_readwrite("X", &CPG_Prim_cpp_t::X)
            .def_readwrite("U", &CPG_Prim_cpp_t::U)
            ;

    py::class_<CPG_Dual_cpp_t>(m, "cpg_dual")
            .def(py::init<>())
            .def_readwrite("d0", &CPG_Dual_cpp_t::d0)
            .def_readwrite("d1", &CPG_Dual_cpp_t::d1)
            .def_readwrite("d2", &CPG_Dual_cpp_t::d2)
            .def_readwrite("d3", &CPG_Dual_cpp_t::d3)
            .def_readwrite("d4", &CPG_Dual_cpp_t::d4)
            .def_readwrite("d5", &CPG_Dual_cpp_t::d5)
            .def_readwrite("d6", &CPG_Dual_cpp_t::d6)
            .def_readwrite("d7", &CPG_Dual_cpp_t::d7)
            .def_readwrite("d8", &CPG_Dual_cpp_t::d8)
            .def_readwrite("d9", &CPG_Dual_cpp_t::d9)
            .def_readwrite("d10", &CPG_Dual_cpp_t::d10)
            .def_readwrite("d11", &CPG_Dual_cpp_t::d11)
            .def_readwrite("d12", &CPG_Dual_cpp_t::d12)
            .def_readwrite("d13", &CPG_Dual_cpp_t::d13)
            .def_readwrite("d14", &CPG_Dual_cpp_t::d14)
            .def_readwrite("d15", &CPG_Dual_cpp_t::d15)
            .def_readwrite("d16", &CPG_Dual_cpp_t::d16)
            .def_readwrite("d17", &CPG_Dual_cpp_t::d17)
            .def_readwrite("d18", &CPG_Dual_cpp_t::d18)
            .def_readwrite("d19", &CPG_Dual_cpp_t::d19)
            .def_readwrite("d20", &CPG_Dual_cpp_t::d20)
            .def_readwrite("d21", &CPG_Dual_cpp_t::d21)
            .def_readwrite("d22", &CPG_Dual_cpp_t::d22)
            .def_readwrite("d23", &CPG_Dual_cpp_t::d23)
            .def_readwrite("d24", &CPG_Dual_cpp_t::d24)
            .def_readwrite("d25", &CPG_Dual_cpp_t::d25)
            .def_readwrite("d26", &CPG_Dual_cpp_t::d26)
            .def_readwrite("d27", &CPG_Dual_cpp_t::d27)
            .def_readwrite("d28", &CPG_Dual_cpp_t::d28)
            .def_readwrite("d29", &CPG_Dual_cpp_t::d29)
            .def_readwrite("d30", &CPG_Dual_cpp_t::d30)
            .def_readwrite("d31", &CPG_Dual_cpp_t::d31)
            .def_readwrite("d32", &CPG_Dual_cpp_t::d32)
            .def_readwrite("d33", &CPG_Dual_cpp_t::d33)
            .def_readwrite("d34", &CPG_Dual_cpp_t::d34)
            .def_readwrite("d35", &CPG_Dual_cpp_t::d35)
            .def_readwrite("d36", &CPG_Dual_cpp_t::d36)
            .def_readwrite("d37", &CPG_Dual_cpp_t::d37)
            .def_readwrite("d38", &CPG_Dual_cpp_t::d38)
            .def_readwrite("d39", &CPG_Dual_cpp_t::d39)
            .def_readwrite("d40", &CPG_Dual_cpp_t::d40)
            .def_readwrite("d41", &CPG_Dual_cpp_t::d41)
            .def_readwrite("d42", &CPG_Dual_cpp_t::d42)
            .def_readwrite("d43", &CPG_Dual_cpp_t::d43)
            .def_readwrite("d44", &CPG_Dual_cpp_t::d44)
            .def_readwrite("d45", &CPG_Dual_cpp_t::d45)
            .def_readwrite("d46", &CPG_Dual_cpp_t::d46)
            .def_readwrite("d47", &CPG_Dual_cpp_t::d47)
            .def_readwrite("d48", &CPG_Dual_cpp_t::d48)
            .def_readwrite("d49", &CPG_Dual_cpp_t::d49)
            .def_readwrite("d50", &CPG_Dual_cpp_t::d50)
            ;

    py::class_<CPG_Info_cpp_t>(m, "cpg_info")
            .def(py::init<>())
            .def_readwrite("obj_val", &CPG_Info_cpp_t::obj_val)
            .def_readwrite("iter", &CPG_Info_cpp_t::iter)
            .def_readwrite("status", &CPG_Info_cpp_t::status)
            .def_readwrite("pri_res", &CPG_Info_cpp_t::pri_res)
            .def_readwrite("dua_res", &CPG_Info_cpp_t::dua_res)
            .def_readwrite("time", &CPG_Info_cpp_t::time)
            ;

    py::class_<CPG_Result_cpp_t>(m, "cpg_result")
            .def(py::init<>())
            .def_readwrite("cpg_prim", &CPG_Result_cpp_t::prim)
            .def_readwrite("cpg_dual", &CPG_Result_cpp_t::dual)
            .def_readwrite("cpg_info", &CPG_Result_cpp_t::info)
            ;

    m.def("solve", &solve_cpp);

    m.def("set_solver_default_settings", &cpg_set_solver_default_settings);
    m.def("set_solver_rho", &cpg_set_solver_rho);
    m.def("set_solver_max_iter", &cpg_set_solver_max_iter);
    m.def("set_solver_eps_abs", &cpg_set_solver_eps_abs);
    m.def("set_solver_eps_rel", &cpg_set_solver_eps_rel);
    m.def("set_solver_eps_prim_inf", &cpg_set_solver_eps_prim_inf);
    m.def("set_solver_eps_dual_inf", &cpg_set_solver_eps_dual_inf);
    m.def("set_solver_alpha", &cpg_set_solver_alpha);
    m.def("set_solver_scaled_termination", &cpg_set_solver_scaled_termination);
    m.def("set_solver_check_termination", &cpg_set_solver_check_termination);
    m.def("set_solver_warm_start", &cpg_set_solver_warm_start);

}
