
/*
Auto-generated by CVXPYgen on July 18, 2023 at 14:40:23.
Content: Declarations for Python binding with pybind11.
*/

// User-defined parameters
struct CPG_Params_cpp_t {
    std::array<double, 36> Psqrt;
    std::array<double, 36> Qsqrt;
    std::array<double, 9> Rsqrt;
    std::array<double, 36> A;
    std::array<double, 18> B;
    std::array<double, 6> x_init;
};

// Flags for updated user-defined parameters
struct CPG_Updated_cpp_t {
    bool Psqrt;
    bool Qsqrt;
    bool Rsqrt;
    bool A;
    bool B;
    bool x_init;
};

// Primal solution
struct CPG_Prim_cpp_t {
    std::array<double, 66> X;
    std::array<double, 30> U;
};

// Dual solution
struct CPG_Dual_cpp_t {
    std::array<double, 60> d0;
    std::array<double, 30> d1;
    std::array<double, 6> d2;
};

// Solver information
struct CPG_Info_cpp_t {
    double obj_val;
    int iter;
    char* status;
    double pri_res;
    double dua_res;
    double time;
};

// Solution and solver information
struct CPG_Result_cpp_t {
    CPG_Prim_cpp_t prim;
    CPG_Dual_cpp_t dual;
    CPG_Info_cpp_t info;
};

// Main solve function
CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp);
