
/*
Auto-generated by CVXPYgen on August 20, 2023 at 23:19:56.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static c_int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_x_final(0, 4.00000000000000000000);
  cpg_update_x_init(0, 1.00000000000000000000);
  cpg_update_A(0, 1.00000000000000000000);
  cpg_update_B(0, 0.00500000000000000097);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<22; i++) {
    printf("X[%lld] = %f\n", i, CPG_Result.prim->X[i]);
  }
  for(i=0; i<10; i++) {
    printf("U[%lld] = %f\n", i, CPG_Result.prim->U[i]);
  }

  // Print dual solution
  for(i=0; i<2; i++) {
    printf("d0[%lld] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<2; i++) {
    printf("d1[%lld] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<2; i++) {
    printf("d2[%lld] = %f\n", i, CPG_Result.dual->d2[i]);
  }
  for(i=0; i<2; i++) {
    printf("d3[%lld] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  for(i=0; i<2; i++) {
    printf("d4[%lld] = %f\n", i, CPG_Result.dual->d4[i]);
  }
  for(i=0; i<2; i++) {
    printf("d5[%lld] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<2; i++) {
    printf("d6[%lld] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  for(i=0; i<2; i++) {
    printf("d7[%lld] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  for(i=0; i<2; i++) {
    printf("d8[%lld] = %f\n", i, CPG_Result.dual->d8[i]);
  }
  for(i=0; i<2; i++) {
    printf("d9[%lld] = %f\n", i, CPG_Result.dual->d9[i]);
  }
  for(i=0; i<2; i++) {
    printf("d10[%lld] = %f\n", i, CPG_Result.dual->d10[i]);
  }
  for(i=0; i<2; i++) {
    printf("d11[%lld] = %f\n", i, CPG_Result.dual->d11[i]);
  }
  for(i=0; i<2; i++) {
    printf("d12[%lld] = %f\n", i, CPG_Result.dual->d12[i]);
  }
  printf("d13 = %f\n", CPG_Result.dual->d13);
  printf("d14 = %f\n", CPG_Result.dual->d14);
  for(i=0; i<2; i++) {
    printf("d15[%lld] = %f\n", i, CPG_Result.dual->d15[i]);
  }
  for(i=0; i<2; i++) {
    printf("d16[%lld] = %f\n", i, CPG_Result.dual->d16[i]);
  }
  printf("d17 = %f\n", CPG_Result.dual->d17);
  printf("d18 = %f\n", CPG_Result.dual->d18);
  for(i=0; i<2; i++) {
    printf("d19[%lld] = %f\n", i, CPG_Result.dual->d19[i]);
  }
  for(i=0; i<2; i++) {
    printf("d20[%lld] = %f\n", i, CPG_Result.dual->d20[i]);
  }
  printf("d21 = %f\n", CPG_Result.dual->d21);
  printf("d22 = %f\n", CPG_Result.dual->d22);
  for(i=0; i<2; i++) {
    printf("d23[%lld] = %f\n", i, CPG_Result.dual->d23[i]);
  }
  for(i=0; i<2; i++) {
    printf("d24[%lld] = %f\n", i, CPG_Result.dual->d24[i]);
  }
  printf("d25 = %f\n", CPG_Result.dual->d25);
  printf("d26 = %f\n", CPG_Result.dual->d26);
  for(i=0; i<2; i++) {
    printf("d27[%lld] = %f\n", i, CPG_Result.dual->d27[i]);
  }
  for(i=0; i<2; i++) {
    printf("d28[%lld] = %f\n", i, CPG_Result.dual->d28[i]);
  }
  printf("d29 = %f\n", CPG_Result.dual->d29);
  printf("d30 = %f\n", CPG_Result.dual->d30);
  for(i=0; i<2; i++) {
    printf("d31[%lld] = %f\n", i, CPG_Result.dual->d31[i]);
  }
  for(i=0; i<2; i++) {
    printf("d32[%lld] = %f\n", i, CPG_Result.dual->d32[i]);
  }
  printf("d33 = %f\n", CPG_Result.dual->d33);
  printf("d34 = %f\n", CPG_Result.dual->d34);
  for(i=0; i<2; i++) {
    printf("d35[%lld] = %f\n", i, CPG_Result.dual->d35[i]);
  }
  for(i=0; i<2; i++) {
    printf("d36[%lld] = %f\n", i, CPG_Result.dual->d36[i]);
  }
  printf("d37 = %f\n", CPG_Result.dual->d37);
  printf("d38 = %f\n", CPG_Result.dual->d38);
  for(i=0; i<2; i++) {
    printf("d39[%lld] = %f\n", i, CPG_Result.dual->d39[i]);
  }
  for(i=0; i<2; i++) {
    printf("d40[%lld] = %f\n", i, CPG_Result.dual->d40[i]);
  }
  printf("d41 = %f\n", CPG_Result.dual->d41);
  printf("d42 = %f\n", CPG_Result.dual->d42);
  for(i=0; i<2; i++) {
    printf("d43[%lld] = %f\n", i, CPG_Result.dual->d43[i]);
  }
  for(i=0; i<2; i++) {
    printf("d44[%lld] = %f\n", i, CPG_Result.dual->d44[i]);
  }
  printf("d45 = %f\n", CPG_Result.dual->d45);
  printf("d46 = %f\n", CPG_Result.dual->d46);
  for(i=0; i<2; i++) {
    printf("d47[%lld] = %f\n", i, CPG_Result.dual->d47[i]);
  }
  for(i=0; i<2; i++) {
    printf("d48[%lld] = %f\n", i, CPG_Result.dual->d48[i]);
  }
  printf("d49 = %f\n", CPG_Result.dual->d49);
  printf("d50 = %f\n", CPG_Result.dual->d50);

  return 0;

}
