#ifndef WORKSPACE_H
#define WORKSPACE_H

/*
 * This file was autogenerated by OSQP-Python on August 20, 2023 at 23:19:50.
 * 
 * This file contains the prototypes for all the workspace variables needed
 * by OSQP. The actual data is contained inside workspace.c.
 */

#include "types.h"
#include "qdldl_interface.h"

// Data structure prototypes
extern csc Pdata;
extern csc Adata;
extern c_float qdata[61];
extern c_float ldata[111];
extern c_float udata[111];
extern OSQPData data;

// Settings structure prototype
extern OSQPSettings settings;

// Scaling structure prototypes
extern c_float Dscaling[61];
extern c_float Dinvscaling[61];
extern c_float Escaling[111];
extern c_float Einvscaling[111];
extern OSQPScaling scaling;

// Prototypes for linsys_solver structure
extern csc linsys_solver_L;
extern c_float linsys_solver_Dinv[172];
extern c_int linsys_solver_P[172];
extern c_float linsys_solver_bp[172];
extern c_float linsys_solver_sol[172];
extern c_float linsys_solver_rho_inv_vec[111];
extern c_int linsys_solver_Pdiag_idx[29];
extern csc linsys_solver_KKT;
extern c_int linsys_solver_PtoKKT[29];
extern c_int linsys_solver_AtoKKT[200];
extern c_int linsys_solver_rhotoKKT[111];
extern QDLDL_float linsys_solver_D[172];
extern QDLDL_int linsys_solver_etree[172];
extern QDLDL_int linsys_solver_Lnz[172];
extern QDLDL_int   linsys_solver_iwork[516];
extern QDLDL_bool  linsys_solver_bwork[172];
extern QDLDL_float linsys_solver_fwork[172];
extern qdldl_solver linsys_solver;

// Prototypes for solution
extern c_float xsolution[61];
extern c_float ysolution[111];

extern OSQPSolution solution;

// Prototype for info structure
extern OSQPInfo info;

// Prototypes for the workspace
extern c_float work_rho_vec[111];
extern c_float work_rho_inv_vec[111];
extern c_int work_constr_type[111];
extern c_float work_x[61];
extern c_float work_y[111];
extern c_float work_z[111];
extern c_float work_xz_tilde[172];
extern c_float work_x_prev[61];
extern c_float work_z_prev[111];
extern c_float work_Ax[111];
extern c_float work_Px[61];
extern c_float work_Aty[61];
extern c_float work_delta_y[111];
extern c_float work_Atdelta_y[61];
extern c_float work_delta_x[61];
extern c_float work_Pdelta_x[61];
extern c_float work_Adelta_x[111];
extern c_float work_D_temp[61];
extern c_float work_D_temp_A[61];
extern c_float work_E_temp[111];

extern OSQPWorkspace workspace;

#endif // ifndef WORKSPACE_H
