
/*
Auto-generated by CVXPYgen on July 18, 2023 at 14:40:23.
Content: Function definitions.
*/

#include "cpg_solve.h"
#include "cpg_workspace.h"
#include "workspace.h"
#include "osqp.h"

static c_int i;
static c_int j;

// Update user-defined parameters
void cpg_update_Psqrt(c_int idx, c_float val){
  cpg_params_vec[idx+0] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Qsqrt(c_int idx, c_float val){
  cpg_params_vec[idx+36] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_Rsqrt(c_int idx, c_float val){
  cpg_params_vec[idx+72] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_A(c_int idx, c_float val){
  cpg_params_vec[idx+81] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_B(c_int idx, c_float val){
  cpg_params_vec[idx+117] = val;
  Canon_Outdated.A = 1;
}

void cpg_update_x_init(c_int idx, c_float val){
  cpg_params_vec[idx+135] = val;
  Canon_Outdated.l = 1;
  Canon_Outdated.u = 1;
}

// Map user-defined to canonical parameters
void cpg_canonicalize_A(){
  for(i=0; i<1338; i++){
    Canon_Params.A->x[i] = 0;
    for(j=canon_A_map.p[i]; j<canon_A_map.p[i+1]; j++){
      Canon_Params.A->x[i] += canon_A_map.x[j]*cpg_params_vec[canon_A_map.i[j]];
    }
  }
}

void cpg_canonicalize_l(){
  for(i=0; i<162; i++){
    Canon_Params.l[i] = 0;
    for(j=canon_l_map.p[i]; j<canon_l_map.p[i+1]; j++){
      Canon_Params.l[i] += canon_l_map.x[j]*cpg_params_vec[canon_l_map.i[j]];
    }
  }
}

void cpg_canonicalize_u(){
  for(i=0; i<252; i++){
    Canon_Params.u[i] = 0;
    for(j=canon_u_map.p[i]; j<canon_u_map.p[i+1]; j++){
      Canon_Params.u[i] += canon_u_map.x[j]*cpg_params_vec[canon_u_map.i[j]];
    }
  }
}

// Retrieve solver info
void cpg_retrieve_info(){
  CPG_Info.obj_val = workspace.info->obj_val;
  CPG_Info.iter = workspace.info->iter;
  CPG_Info.status = workspace.info->status;
  CPG_Info.pri_res = workspace.info->pri_res;
  CPG_Info.dua_res = workspace.info->dua_res;
}

// Solve via canonicalization, canonical solve, retrieval
void cpg_solve(){
  // Canonicalize if necessary
  if (Canon_Outdated.A) {
    cpg_canonicalize_A();
    osqp_update_A(&workspace, Canon_Params.A->x, 0, 0);
  }
  if (Canon_Outdated.l && Canon_Outdated.u) {
    cpg_canonicalize_l();
    cpg_canonicalize_u();
    osqp_update_bounds(&workspace, Canon_Params.l, Canon_Params.u);
  } else if (Canon_Outdated.l) {
    cpg_canonicalize_l();
    osqp_update_lower_bound(&workspace, Canon_Params.l);
  } else if (Canon_Outdated.u) {
    cpg_canonicalize_u();
    osqp_update_upper_bound(&workspace, Canon_Params.u);
  }
  // Solve with OSQP
  osqp_solve(&workspace);
  // Retrieve results
  cpg_retrieve_info();
  // Reset flags for outdated canonical parameters
  Canon_Outdated.P = 0;
  Canon_Outdated.q = 0;
  Canon_Outdated.d = 0;
  Canon_Outdated.A = 0;
  Canon_Outdated.l = 0;
  Canon_Outdated.u = 0;
}

// Update solver settings
void cpg_set_solver_default_settings(){
  osqp_set_default_settings(&settings);
}

void cpg_set_solver_rho(c_float rho_new){
  osqp_update_rho(&workspace, rho_new);
}

void cpg_set_solver_max_iter(c_int max_iter_new){
  osqp_update_max_iter(&workspace, max_iter_new);
}

void cpg_set_solver_eps_abs(c_float eps_abs_new){
  osqp_update_eps_abs(&workspace, eps_abs_new);
}

void cpg_set_solver_eps_rel(c_float eps_rel_new){
  osqp_update_eps_rel(&workspace, eps_rel_new);
}

void cpg_set_solver_eps_prim_inf(c_float eps_prim_inf_new){
  osqp_update_eps_prim_inf(&workspace, eps_prim_inf_new);
}

void cpg_set_solver_eps_dual_inf(c_float eps_dual_inf_new){
  osqp_update_eps_dual_inf(&workspace, eps_dual_inf_new);
}

void cpg_set_solver_alpha(c_float alpha_new){
  osqp_update_alpha(&workspace, alpha_new);
}

void cpg_set_solver_scaled_termination(c_int scaled_termination_new){
  osqp_update_scaled_termination(&workspace, scaled_termination_new);
}

void cpg_set_solver_check_termination(c_int check_termination_new){
  osqp_update_check_termination(&workspace, check_termination_new);
}

void cpg_set_solver_warm_start(c_int warm_start_new){
  osqp_update_warm_start(&workspace, warm_start_new);
}
