
/*
Auto-generated by CVXPYgen on July 18, 2023 at 14:40:23.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static c_int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_Psqrt(0, 1.00000000000000000000);
  cpg_update_Qsqrt(0, 1.00000000000000000000);
  cpg_update_Rsqrt(0, 0.31622776601683794118);
  cpg_update_A(0, 1.00000000000000000000);
  cpg_update_B(0, 0.00000000000000000000);
  cpg_update_x_init(0, 2.00000000000000000000);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<66; i++) {
    printf("X[%lld] = %f\n", i, CPG_Result.prim->X[i]);
  }
  for(i=0; i<30; i++) {
    printf("U[%lld] = %f\n", i, CPG_Result.prim->U[i]);
  }

  // Print dual solution
  for(i=0; i<60; i++) {
    printf("d0[%lld] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<30; i++) {
    printf("d1[%lld] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  for(i=0; i<6; i++) {
    printf("d2[%lld] = %f\n", i, CPG_Result.dual->d2[i]);
  }

  return 0;

}
