
/*
Auto-generated by CVXPYgen on July 18, 2023 at 14:40:23.
Content: Python binding with pybind11.
*/

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <ctime>
#include "cpg_module.hpp"

extern "C" {
    #include "include/cpg_workspace.h"
    #include "include/cpg_solve.h"
}

namespace py = pybind11;

static int i;

CPG_Result_cpp_t solve_cpp(struct CPG_Updated_cpp_t& CPG_Updated_cpp, struct CPG_Params_cpp_t& CPG_Params_cpp){

    // Pass changed user-defined parameter values to the solver
    if (CPG_Updated_cpp.Psqrt) {
        for(i=0; i<36; i++) {
            cpg_update_Psqrt(i, CPG_Params_cpp.Psqrt[i]);
        }
    }
    if (CPG_Updated_cpp.Qsqrt) {
        for(i=0; i<36; i++) {
            cpg_update_Qsqrt(i, CPG_Params_cpp.Qsqrt[i]);
        }
    }
    if (CPG_Updated_cpp.Rsqrt) {
        for(i=0; i<9; i++) {
            cpg_update_Rsqrt(i, CPG_Params_cpp.Rsqrt[i]);
        }
    }
    if (CPG_Updated_cpp.A) {
        for(i=0; i<36; i++) {
            cpg_update_A(i, CPG_Params_cpp.A[i]);
        }
    }
    if (CPG_Updated_cpp.B) {
        for(i=0; i<18; i++) {
            cpg_update_B(i, CPG_Params_cpp.B[i]);
        }
    }
    if (CPG_Updated_cpp.x_init) {
        for(i=0; i<6; i++) {
            cpg_update_x_init(i, CPG_Params_cpp.x_init[i]);
        }
    }

    // Solve
    std::clock_t ASA_start = std::clock();
    cpg_solve();
    std::clock_t ASA_end = std::clock();

    // Arrange and return results
    CPG_Prim_cpp_t CPG_Prim_cpp {};
    for(i=0; i<66; i++) {
        CPG_Prim_cpp.X[i] = CPG_Prim.X[i];
    }
    for(i=0; i<30; i++) {
        CPG_Prim_cpp.U[i] = CPG_Prim.U[i];
    }
    CPG_Dual_cpp_t CPG_Dual_cpp {};
    for(i=0; i<60; i++) {
        CPG_Dual_cpp.d0[i] = CPG_Dual.d0[i];
    }
    for(i=0; i<30; i++) {
        CPG_Dual_cpp.d1[i] = CPG_Dual.d1[i];
    }
    for(i=0; i<6; i++) {
        CPG_Dual_cpp.d2[i] = CPG_Dual.d2[i];
    }
    CPG_Info_cpp_t CPG_Info_cpp {};
    CPG_Info_cpp.obj_val = CPG_Info.obj_val;
    CPG_Info_cpp.iter = CPG_Info.iter;
    CPG_Info_cpp.status = CPG_Info.status;
    CPG_Info_cpp.pri_res = CPG_Info.pri_res;
    CPG_Info_cpp.dua_res = CPG_Info.dua_res;
    CPG_Info_cpp.time = 1.0*(ASA_end-ASA_start) / CLOCKS_PER_SEC;
    CPG_Result_cpp_t CPG_Result_cpp {};
    CPG_Result_cpp.prim = CPG_Prim_cpp;
    CPG_Result_cpp.dual = CPG_Dual_cpp;
    CPG_Result_cpp.info = CPG_Info_cpp;
    return CPG_Result_cpp;

}

PYBIND11_MODULE(cpg_module, m) {

    py::class_<CPG_Params_cpp_t>(m, "cpg_params")
            .def(py::init<>())
            .def_readwrite("Psqrt", &CPG_Params_cpp_t::Psqrt)
            .def_readwrite("Qsqrt", &CPG_Params_cpp_t::Qsqrt)
            .def_readwrite("Rsqrt", &CPG_Params_cpp_t::Rsqrt)
            .def_readwrite("A", &CPG_Params_cpp_t::A)
            .def_readwrite("B", &CPG_Params_cpp_t::B)
            .def_readwrite("x_init", &CPG_Params_cpp_t::x_init)
            ;

    py::class_<CPG_Updated_cpp_t>(m, "cpg_updated")
            .def(py::init<>())
            .def_readwrite("Psqrt", &CPG_Updated_cpp_t::Psqrt)
            .def_readwrite("Qsqrt", &CPG_Updated_cpp_t::Qsqrt)
            .def_readwrite("Rsqrt", &CPG_Updated_cpp_t::Rsqrt)
            .def_readwrite("A", &CPG_Updated_cpp_t::A)
            .def_readwrite("B", &CPG_Updated_cpp_t::B)
            .def_readwrite("x_init", &CPG_Updated_cpp_t::x_init)
            ;

    py::class_<CPG_Prim_cpp_t>(m, "cpg_prim")
            .def(py::init<>())
            .def_readwrite("X", &CPG_Prim_cpp_t::X)
            .def_readwrite("U", &CPG_Prim_cpp_t::U)
            ;

    py::class_<CPG_Dual_cpp_t>(m, "cpg_dual")
            .def(py::init<>())
            .def_readwrite("d0", &CPG_Dual_cpp_t::d0)
            .def_readwrite("d1", &CPG_Dual_cpp_t::d1)
            .def_readwrite("d2", &CPG_Dual_cpp_t::d2)
            ;

    py::class_<CPG_Info_cpp_t>(m, "cpg_info")
            .def(py::init<>())
            .def_readwrite("obj_val", &CPG_Info_cpp_t::obj_val)
            .def_readwrite("iter", &CPG_Info_cpp_t::iter)
            .def_readwrite("status", &CPG_Info_cpp_t::status)
            .def_readwrite("pri_res", &CPG_Info_cpp_t::pri_res)
            .def_readwrite("dua_res", &CPG_Info_cpp_t::dua_res)
            .def_readwrite("time", &CPG_Info_cpp_t::time)
            ;

    py::class_<CPG_Result_cpp_t>(m, "cpg_result")
            .def(py::init<>())
            .def_readwrite("cpg_prim", &CPG_Result_cpp_t::prim)
            .def_readwrite("cpg_dual", &CPG_Result_cpp_t::dual)
            .def_readwrite("cpg_info", &CPG_Result_cpp_t::info)
            ;

    m.def("solve", &solve_cpp);

    m.def("set_solver_default_settings", &cpg_set_solver_default_settings);
    m.def("set_solver_rho", &cpg_set_solver_rho);
    m.def("set_solver_max_iter", &cpg_set_solver_max_iter);
    m.def("set_solver_eps_abs", &cpg_set_solver_eps_abs);
    m.def("set_solver_eps_rel", &cpg_set_solver_eps_rel);
    m.def("set_solver_eps_prim_inf", &cpg_set_solver_eps_prim_inf);
    m.def("set_solver_eps_dual_inf", &cpg_set_solver_eps_dual_inf);
    m.def("set_solver_alpha", &cpg_set_solver_alpha);
    m.def("set_solver_scaled_termination", &cpg_set_solver_scaled_termination);
    m.def("set_solver_check_termination", &cpg_set_solver_check_termination);
    m.def("set_solver_warm_start", &cpg_set_solver_warm_start);

}
